# Generated by Django 5.1.3 on 2024-12-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
