# Generated by Django 5.1.3 on 2024-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
